### ISSUE TITLE
Node ids of dependency graph may not be unique

### ISSUE THREAD

**Issue by sebastianstock** [aiplan4eu/embedded-systems-bridge#11]
The node identifiers in the dependency graph are created from the action's name and actual parameters.
Therefore, if there are multiple instances of the same action with the same parameters in the plan those would appear only once in the dependency graph.

**Comment by franklinselva** [comment]
An attempt was made in #8 to handle this problem. Instead of separate attributes, I have tried to compile the action instance into [executable action representation](https://github.com/aiplan4eu/unified-planning-bridge/blob/922ecde8d990cb5ee905cc0e3b3f84226ab9b039/up_bridge/bridge.py#L375). Eventually, each node is expected to have its own representation.

But the problem in dependency graph may be due to the node name produced when translating plans.

**Comment by sebastianstock** [comment]
> But the problem in dependency graph may be due to the node name produced when translating plans.

Yes, indeed I think the problem is the node name. We should add a unique id, .e.g, the position  of the action in the plan.
